name: Generate pacman animation

on:
  schedule:
    # Se ejecuta cada 12 horas (Corregido: 0 */12 * * *)
    - cron: "0 */12 * * *"
  
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate-pacman-graph
        uses: Platane/snk@v3
        with:
          github_user_name: JHERICO-AJ
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ESTE PASO ES EL QUE TE FALTABA: 
      # Guarda la imagen en la rama 'output' para que el README pueda verla
      - name: push pacman-contribution-graph to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
